# Generated by Django 5.0.4 on 2024-04-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_members_delete_groupmembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
